/* =========================================================
   admin/app.js
   Login/setup, tabs, lists, publish (commit) flow.
   ========================================================= */
"use strict";
(function (A) {
  const { h } = A;
  const S = A.S;
  const app = document.getElementById("app");

  const SESSION = "adm_session";
  const FAILS = "adm_fails";
  const SESSION_MIN = 60;
  const WORKS_HEADER = "Works data. Generated by the admin page (/admin). Safe to edit by hand.";
  const SITE_HEADER = "Site data (About). Generated by the admin page (/admin).";
  const MAX_FILE = 50 * 1024 * 1024;

  const FIXED = [
    { path: "images/home/hero.mp4", label: "Home background video", kind: "video", accept: "video/mp4", ext: "mp4" },
    { path: "cv/cv-ko.pdf", label: "CV · Korean", kind: "pdf", accept: "application/pdf", ext: "pdf" },
    { path: "cv/cv-en.pdf", label: "CV · English", kind: "pdf", accept: "application/pdf", ext: "pdf" },
    { path: "cv/cv-ja.pdf", label: "CV · Japanese", kind: "pdf", accept: "application/pdf", ext: "pdf" },
  ];
  const FIXED_PATHS = new Set(FIXED.map((f) => f.path));

  const ctx = { gh: null };
  let base = null; // last state that matched the repository
  let tab = "works";
  let editing = null;

  /* ---------- Storage utils ---------- */
  const store = {
    get(area, k) { try { return JSON.parse(window[area].getItem(k)); } catch (e) { return null; } },
    set(area, k, v) { try { window[area].setItem(k, JSON.stringify(v)); } catch (e) { /* ignore */ } },
    del(area, k) { try { window[area].removeItem(k); } catch (e) { /* ignore */ } },
  };

  function friendly(e) {
    if (!e) return "Unknown error";
    if (e.message === "WRONG_PASSWORD") return "Incorrect password.";
    if (e.status === 401) return "The token is invalid or has expired.";
    if (e.status === 403) return "Permission denied or rate-limited. Check the token's Contents permission (Read and write) and its repository access.";
    if (e.status === 404) return "Repository or branch not found. Check the owner, repository, branch, and the token's repository selection.";
    if (e.status === 409 || e.status === 422) return "GitHub rejected the change (" + e.message + "). It may have been edited elsewhere. Reload and try again.";
    if (e instanceof TypeError) return "Network error. Check your internet connection.";
    return e.message || String(e);
  }

  async function busy(msg, fn) {
    const txt = h("p", { text: msg });
    const bar = h("i");
    const ov = h("div", { class: "overlay" }, h("div", { class: "modal" }, h("h3", { text: "Please wait" }), txt, h("div", { class: "bar" }, bar)));
    document.body.append(ov);
    try {
      return await fn((t, pct) => {
        if (t) txt.textContent = t;
        if (pct != null) bar.style.width = pct + "%";
      });
    } finally {
      ov.remove();
    }
  }

  function modal(title, body, buttons) {
    return new Promise((resolve) => {
      const close = (v) => { ov.remove(); resolve(v); };
      const ov = h("div", { class: "overlay" },
        h("div", { class: "modal", role: "dialog" },
          h("h3", { text: title }), body,
          h("div", { class: "btns" }, buttons.map((b) => h("button", { type: "button", class: "btn " + (b.cls || ""), text: b.text, onclick: () => close(b.value) })))
        )
      );
      document.body.append(ov);
    });
  }

  /* ---------- Session ---------- */
  function saveSession() {
    const g = ctx.gh;
    store.set("sessionStorage", SESSION, { token: g.token, owner: g.owner, repo: g.repo, branch: g.branch, exp: Date.now() + SESSION_MIN * 60000 });
  }
  function readSession() {
    const s = store.get("sessionStorage", SESSION);
    if (!s || !s.token || !s.exp || s.exp < Date.now()) { store.del("sessionStorage", SESSION); return null; }
    return s;
  }

  /* ---------- Shared screen frame ---------- */
  function gate(title, sub, ...kids) {
    app.replaceChildren(h("div", { class: "gate" }, h("div", { class: "gate-box" }, h("h1", { text: title }), sub ? h("p", { class: "sub", text: sub }) : null, ...kids)));
  }
  const field = (label, input, hint) => h("div", { class: "f" }, h("label", { class: "f-label", text: label }), input, hint ? A.hint(hint) : null);
  const pwInput = (ph) => h("input", { class: "in", type: "password", autocomplete: "off", placeholder: ph || "" });

  /* =========================================================
     First-time setup (create the vault)
     ========================================================= */
  function renderSetup() {
    const m = location.hostname.match(/^([^.]+)\.github\.io$/);
    const owner = h("input", { class: "in", type: "text", value: m ? m[1] : "", placeholder: "GitHub username", autocomplete: "off" });
    const repo = h("input", { class: "in", type: "text", placeholder: "Repository name", autocomplete: "off" });
    const branch = h("input", { class: "in", type: "text", placeholder: "Leave blank for the default branch", autocomplete: "off" });
    const token = pwInput("github_pat_...");
    const pw = pwInput("At least 10 characters");
    const pw2 = pwInput("Repeat password");
    const err = h("p", { class: "err" });
    const btn = h("button", { class: "btn block", type: "submit", text: "Set up and start" });

    const form = h("form", {
      onsubmit: async (e) => {
        e.preventDefault();
        err.textContent = "";
        const o = owner.value.trim(), r = repo.value.trim(), t = token.value.trim();
        if (!o || !r || !t) { err.textContent = "Enter the owner, repository, and token."; return; }
        if (pw.value.length < 10) { err.textContent = "The password must be at least 10 characters."; return; }
        if (pw.value !== pw2.value) { err.textContent = "The passwords do not match."; return; }
        btn.disabled = true;
        try {
          await busy("Verifying the token and creating the vault… (takes a few seconds)", async () => {
            const gh = new A.GH({ token: t, owner: o, repo: r, branch: branch.value.trim() || "main" });
            const info = await gh.getRepo();
            if (info.permissions && info.permissions.push === false) throw new Error("This token cannot write to the repository. Set Contents permission to Read and write.");
            if (!branch.value.trim()) gh.branch = info.default_branch;
            await gh.json(gh.rp("/git/ref/heads/" + gh.branch));
            const vault = await A.vault.seal(pw.value, { token: t }, { owner: o, repo: r, branch: gh.branch });
            await gh.putFile("admin/vault.json", JSON.stringify(vault, null, 2) + "\n", "Admin: set up vault");
            ctx.gh = gh;
          });
          saveSession();
          A.toast("Setup complete. The password-locked vault was saved to the repository.", "ok");
          await enter();
        } catch (e2) {
          err.textContent = friendly(e2);
        }
        btn.disabled = false;
      },
    },
      h("div", { class: "note-box" },
        "One-time setup. Create a ", h("b", { text: "fine-grained personal access token" }), " on GitHub and paste it below.",
        h("ol", null,
          h("li", { text: "GitHub → Settings → Developer settings → Fine-grained tokens → Generate" }),
          h("li", { text: "Repository access: Only select repositories → this portfolio repository only" }),
          h("li", { text: "Permissions → Contents: Read and write" }),
          h("li", { text: "Expiration: as long as allowed (up to 1 year)" })
        ),
        h("div", { text: "The token is encrypted with your password in this browser before it is saved to the repository. It is never stored as plain text." })
      ),
      h("div", { class: "row2" }, field("GitHub username", owner), field("Repository", repo)),
      field("Branch", branch),
      field("Token", token),
      field("Admin password", pw, "This password is the key. Use a long phrase you do not use anywhere else."),
      field("Confirm password", pw2),
      err, btn
    );
    gate("Admin setup", "Choose a password to open the admin page.", form);
    owner.value ? repo.focus() : owner.focus();
  }

  /* =========================================================
     Login
     ========================================================= */
  function renderLogin(vault, notice) {
    const pw = pwInput("Password");
    const err = h("p", { class: "err", text: notice || "" });
    const btn = h("button", { class: "btn block", type: "submit", text: "Sign in" });
    let timer = 0;

    const lockLeft = () => { const f = store.get("localStorage", FAILS) || { n: 0, until: 0 }; return Math.max(0, Math.ceil((f.until - Date.now()) / 1000)); };
    const tick = () => {
      const s = lockLeft();
      btn.disabled = s > 0;
      if (s > 0) { err.textContent = `Too many attempts. Try again in ${s}s.`; timer = setTimeout(tick, 500); }
      else if (/Too many attempts/.test(err.textContent)) err.textContent = "";
    };

    const form = h("form", {
      onsubmit: async (e) => {
        e.preventDefault();
        if (lockLeft() > 0 || !pw.value) return;
        err.textContent = "";
        btn.disabled = true;
        try {
          const payload = await busy("Checking…", () => A.vault.open(pw.value, vault));
          store.del("localStorage", FAILS);
          ctx.gh = new A.GH({ token: payload.token, owner: vault.owner, repo: vault.repo, branch: vault.branch });
          pw.value = "";
          saveSession();
          await enter();
          return;
        } catch (e2) {
          if (e2.message === "WRONG_PASSWORD") {
            const f = store.get("localStorage", FAILS) || { n: 0, until: 0 };
            f.n += 1;
            f.until = f.n >= 3 ? Date.now() + Math.min(60, Math.pow(2, f.n - 2)) * 1000 : 0;
            store.set("localStorage", FAILS, f);
            err.textContent = "Incorrect password.";
          } else err.textContent = friendly(e2);
        }
        pw.value = "";
        tick();
        if (lockLeft() === 0) btn.disabled = false;
      },
    }, field("Password", pw), err, btn,
      h("p", { class: "hint" },
        h("button", { type: "button", class: "btn ghost sm", text: "Replace token / expired", onclick: () => { clearTimeout(timer); renderReplaceToken(vault); } })
      )
    );
    gate("Admin", "eunsumoon.com", form);
    pw.focus();
    tick();
  }

  /* Token replacement from the login screen (password unchanged) */
  function renderReplaceToken(vault) {
    const pw = pwInput("Current password");
    const token = pwInput("New token github_pat_...");
    const err = h("p", { class: "err" });
    const btn = h("button", { class: "btn block", type: "submit", text: "Replace token" });
    const form = h("form", {
      onsubmit: async (e) => {
        e.preventDefault();
        err.textContent = "";
        if (!pw.value || !token.value.trim()) { err.textContent = "Enter your password and the new token."; return; }
        btn.disabled = true;
        try {
          const r = await busy("Replacing…", () => rekey(vault, pw.value, "", token.value.trim()));
          ctx.gh = r.gh;
          saveSession();
          A.toast("Token replaced.", "ok");
          await enter();
          return;
        } catch (e2) { err.textContent = friendly(e2); }
        btn.disabled = false;
      },
    }, field("Current password", pw), field("New token", token, "A newly issued token for the same repository with Contents: Read and write."), err, btn,
      h("p", { class: "hint" }, h("button", { type: "button", class: "btn ghost sm", text: "← Back", onclick: () => renderLogin(vault) })));
    gate("Replace token", "Only the token changes. Your password stays the same.", form);
  }

  async function rekey(vault, currentPw, newPw, newToken) {
    const cur = await A.vault.open(currentPw, vault);
    const token = newToken || cur.token;
    const gh = new A.GH({ token, owner: vault.owner, repo: vault.repo, branch: vault.branch });
    await gh.getRepo();
    const nv = await A.vault.seal(newPw || currentPw, { token }, vault);
    await gh.putFile("admin/vault.json", JSON.stringify(nv, null, 2) + "\n", "Admin: update vault");
    return { vault: nv, gh };
  }

  /* =========================================================
     Load data / compute state
     ========================================================= */
  async function loadData() {
    const gh = ctx.gh;
    const [wt, st, tree] = await Promise.all([gh.getText("data/works.js"), gh.getText("data/site.js"), gh.getTreePaths()]);
    if (wt == null || st == null) throw new Error("data/works.js or data/site.js is missing from the repository. Upload the updated site files (including the data folder) to GitHub first.");
    const rawWorks = A.parseDataFile(wt, "WORKS_DATA");
    const rawSite = A.parseDataFile(st, "SITE_DATA");
    S.gh = gh;
    S.tree = tree;
    S.works = rawWorks.map(A.toEdit);
    S.site = A.siteToEdit(rawSite);
    S.files.forEach((v) => URL.revokeObjectURL(v.url));
    S.files.clear();
    S.deletes.clear();
    baseline(rawWorks);
    editing = null;
  }

  function baseline(rawWorks) {
    base = {
      wj: JSON.stringify(S.works.map(A.serializeWork)),
      sj: JSON.stringify(A.serializeSite(S.site)),
      ids: (rawWorks || S.works).map((w) => w.id),
      refs: A.refsOf(rawWorks || S.works.map(A.serializeWork)),
    };
    S.works.forEach((w) => { delete w._new; });
  }

  const pagePath = (id) => `works/project-${id}.html`;

  function compute() {
    const works = S.works.map(A.serializeWork);
    const wj = JSON.stringify(works);
    const sj = JSON.stringify(A.serializeSite(S.site));
    const refs = A.refsOf(works);
    const ids = works.map((w) => w.id);
    const up = [...S.files.keys()].filter((p) => refs.has(p) || FIXED_PATHS.has(p));
    const orphans = [...base.refs].filter((p) => !refs.has(p) && S.tree.has(p) && p.startsWith("images/works/") && !FIXED_PATHS.has(p));
    return {
      works, wj, sj, refs, ids, up, orphans,
      wChanged: wj !== base.wj,
      sChanged: sj !== base.sj,
      newPages: ids.filter((id) => !S.tree.has(pagePath(id))),
      delPages: base.ids.filter((id) => !ids.includes(id) && S.tree.has(pagePath(id))),
    };
  }
  const isDirty = () => { const c = compute(); return c.wChanged || c.sChanged || c.up.length > 0; };

  /* =========================================================
     Shell (top bar, tabs, bottom publish bar)
     ========================================================= */
  let mainEl, barEl, barMsg, barPub, barRevert;
  const TABS = [["works", "Works"], ["about", "About"], ["home", "Home · CV"], ["settings", "Settings"]];

  function buildShell() {
    const tabs = h("div", { class: "tabs", role: "tablist" }, TABS.map(([k, label]) =>
      h("button", { type: "button", dataset: { tab: k }, class: k === tab ? "is-active" : "", text: label, onclick: () => { tab = k; editing = null; render(); window.scrollTo(0, 0); } })
    ));
    const top = h("header", { class: "topbar" },
      h("div", { class: "brand" }, "Admin", h("small", { text: ctx.gh.owner + "/" + ctx.gh.repo })),
      tabs,
      h("div", { class: "top-right" },
        h("a", { href: "../", target: "_blank", rel: "noopener", text: "View site ↗" }),
        h("button", { type: "button", class: "btn ghost sm", text: "Sign out", onclick: logout })
      )
    );
    mainEl = h("main", { class: "wrap" });
    barMsg = h("span", { class: "msg" });
    barRevert = h("button", { type: "button", class: "btn ghost sm", text: "Discard changes", onclick: revert });
    barPub = h("button", { type: "button", class: "btn", text: "Publish", onclick: publish });
    barEl = h("div", { class: "pubbar" }, barMsg, barRevert, barPub);
    app.replaceChildren(top, mainEl, barEl);
    updateBar();
  }

  let raf = 0;
  S.onChange = () => { cancelAnimationFrame(raf); raf = requestAnimationFrame(updateBar); };

  function updateBar() {
    if (!barEl) return;
    const c = compute();
    const parts = [];
    if (c.wChanged) parts.push("Works");
    if (c.sChanged) parts.push("About");
    if (c.up.length) parts.push(c.up.length + (c.up.length === 1 ? " file" : " files"));
    barEl.classList.toggle("is-on", parts.length > 0);
    barMsg.textContent = parts.length ? "Unpublished changes: " + parts.join(", ") + " · Publish to update the site" : "";
  }

  function logout() {
    if (isDirty() && !confirm("Unpublished changes will be lost. Sign out?")) return;
    store.del("sessionStorage", SESSION);
    location.reload();
  }

  async function revert() {
    if (!confirm("Discard all unpublished changes and reload the repository's current content. Continue?")) return;
    try { await busy("Reloading…", loadData); render(); updateBar(); }
    catch (e) { A.toast(friendly(e), "err"); }
  }

  window.addEventListener("beforeunload", (e) => {
    if (barEl && isDirty()) { e.preventDefault(); e.returnValue = ""; }
  });

  /* =========================================================
     Screens: Works / About / Home·CV / Settings
     ========================================================= */
  function render() {
    document.querySelectorAll(".tabs button").forEach((b) => b.classList.toggle("is-active", b.dataset.tab === tab));
    mainEl.replaceChildren();
    if (tab === "works") renderWorks();
    else if (tab === "about") mainEl.append(A.buildAboutEditor(S.site));
    else if (tab === "home") renderHome();
    else renderSettings();
    updateBar();
  }

  function nextId() {
    let max = 0;
    S.works.forEach((w) => { max = Math.max(max, parseInt(w.id, 10) || 0); });
    S.tree.forEach((p) => { const m = p.match(/^works\/project-(\d+)\.html$/); if (m) max = Math.max(max, parseInt(m[1], 10)); });
    return String(max + 1).padStart(2, "0");
  }

  function renderWorks() {
    if (editing) {
      mainEl.append(A.buildWorkEditor(editing, () => { editing = null; render(); window.scrollTo(0, 0); }));
      return;
    }
    const list = h("ul", { class: "w-list" });
    const move = (i, d) => {
      const j = i + d;
      if (j < 0 || j >= S.works.length) return;
      [S.works[i], S.works[j]] = [S.works[j], S.works[i]];
      S.onChange(); render();
    };
    S.works.forEach((w, i) => {
      const thumb = w.listThumb || w.image;
      list.append(
        h("li", { class: "w-row" + (w._new ? " is-new" : "") },
          h("span", { class: "no", text: String(i + 1).padStart(2, "0") }),
          h("div", { class: "th" }, thumb ? h("img", { src: S.urlFor(thumb), alt: "", loading: "lazy" }) : h("span", { class: "ph", text: "None" })),
          h("div", { class: "tt" }, h("strong", { text: w.titles.en || w.titles.ko || "(Untitled)" }), h("span", { text: [w.tags.en || w.tags.ko, w.year].filter(Boolean).join(" · ") })),
          h("div", { class: "acts" },
            h("button", { type: "button", class: "ic", title: "Move up", text: "↑", onclick: () => move(i, -1) }),
            h("button", { type: "button", class: "ic", title: "Move down", text: "↓", onclick: () => move(i, 1) }),
            h("button", { type: "button", class: "btn sm ghost", text: "Edit", onclick: () => { editing = w; render(); window.scrollTo(0, 0); } }),
            h("button", {
              type: "button", class: "ic danger", title: "Delete", text: "✕",
              onclick: () => {
                if (!confirm(`Delete "${w.titles.en || w.titles.ko || "Untitled"}"?\nBefore publishing, you can undo this with "Discard changes".`)) return;
                S.works.splice(i, 1); S.onChange(); render();
              },
            })
          )
        )
      );
    });
    mainEl.append(
      h("div", { class: "page-head" },
        h("div", null, h("h2", { text: "Works" }), h("p", { text: "The order of this list is the order and numbering shown on the site." })),
        h("button", {
          type: "button", class: "btn", text: "＋ New work",
          onclick: () => { const w = A.newWork(nextId()); w._new = true; S.works.unshift(w); S.onChange(); editing = w; render(); window.scrollTo(0, 0); },
        })
      ),
      list
    );
  }

  function renderHome() {
    const wrap = h("div", { class: "card" }, h("h3", { text: "Home video · CV files" }));
    wrap.append(A.hint("Choosing a file replaces the current one under the same name. After publishing, the old file may still appear for up to 10 minutes because of browser and CDN caching."));
    const draw = () => {
      wrap.querySelectorAll(".slot").forEach((n) => n.remove());
      FIXED.forEach((f) => {
        const staged = S.files.get(f.path);
        const input = h("input", {
          type: "file", accept: f.accept, hidden: true,
          onchange: (e) => {
            const file = e.target.files[0];
            e.target.value = "";
            if (!file) return;
            if (A.path.ext(file.name) !== f.ext) { A.toast(`Only .${f.ext} files are allowed.`, "err"); return; }
            if (file.size > MAX_FILE) { A.toast(`File is too large (${A.fmtSize(file.size)}). Keep it under 50 MB.`, "err"); return; }
            S.stage(f.path, file);
            draw();
          },
        });
        const url = S.urlFor(A.path.enc(f.path));
        wrap.append(
          h("div", { class: "slot" },
            h("div", { class: "prev" }, f.kind === "video" ? h("video", { src: url + "#t=0.1", muted: true, playsinline: true, controls: true, preload: "metadata" }) : h("span", { class: "pdf", text: "PDF" })),
            h("div", null,
              h("strong", { text: f.label }),
              h("div", { class: "state" + (staged ? " pending" : ""), text: staged ? `Replacement pending: ${A.fmtSize(staged.blob.size)} (applied on publish)` : "File currently on the site" }),
              h("code", { class: "path", text: f.path }),
              h("div", { class: "btns" },
                h("button", { type: "button", class: "btn sm", text: "Choose file", onclick: () => input.click() }),
                staged ? h("button", { type: "button", class: "btn sm ghost", text: "Cancel replacement", onclick: () => { S.unstage(f.path); draw(); } }) : null,
                f.kind === "pdf" ? h("a", { class: "btn sm ghost", href: url, target: "_blank", rel: "noopener", text: "Open" }) : null,
                input
              )
            )
          )
        );
      });
    };
    draw();
    mainEl.append(h("div", { class: "page-head" }, h("div", null, h("h2", { text: "Home · CV" }))), wrap);
  }

  function renderSettings() {
    const cur = pwInput(), np = pwInput("Leave blank to keep"), np2 = pwInput(), nt = pwInput("Leave blank to keep");
    const err = h("p", { class: "err" });
    const btn = h("button", { class: "btn", type: "submit", text: "Save" });
    const form = h("form", {
      onsubmit: async (e) => {
        e.preventDefault();
        err.textContent = "";
        if (!cur.value) { err.textContent = "Enter your current password."; return; }
        if (!np.value && !nt.value.trim()) { err.textContent = "Nothing to change."; return; }
        if (np.value && np.value.length < 10) { err.textContent = "The new password must be at least 10 characters."; return; }
        if (np.value !== np2.value) { err.textContent = "The new passwords do not match."; return; }
        btn.disabled = true;
        try {
          await busy("Saving…", async () => {
            const text = await ctx.gh.getText("admin/vault.json");
            if (!text) throw new Error("vault.json was not found in the repository.");
            const r = await rekey(JSON.parse(text), cur.value, np.value, nt.value.trim());
            ctx.gh = r.gh; S.gh = r.gh;
          });
          saveSession();
          [cur, np, np2, nt].forEach((i) => (i.value = ""));
          A.toast("Saved. Until the site redeploys (1 to 3 minutes), the old password may still work.", "ok");
        } catch (e2) { err.textContent = friendly(e2); }
        btn.disabled = false;
      },
    },
      field("Current password (required)", cur),
      field("New password", np),
      field("Confirm new password", np2),
      field("New GitHub token", nt, "Enter only if the token has expired or you want to change it."),
      err, btn
    );
    mainEl.append(
      h("div", { class: "page-head" }, h("div", null, h("h2", { text: "Settings" }))),
      h("div", { class: "set-grid" },
        h("dl", { class: "kv" },
          h("dt", { text: "Repository" }), h("dd", { text: ctx.gh.owner + "/" + ctx.gh.repo }),
          h("dt", { text: "Branch" }), h("dd", { text: ctx.gh.branch }),
          h("dt", { text: "Session" }), h("dd", { text: "Ends when you close this tab or sign out (max " + SESSION_MIN + " min)" })
        ),
        h("div", { class: "card" }, h("h3", { text: "Change password · token" }), form,
          A.hint("If the password may have leaked, revoke the token on GitHub and replace it with a newly issued one."))
      )
    );
  }

  /* =========================================================
     Publish
     ========================================================= */
  function validate(c) {
    const errors = [], warns = [];
    c.works.forEach((w, i) => {
      const name = `Work ${String(i + 1).padStart(2, "0")}`;
      const t = w.titles;
      if (!(t.ko || t.en || t.ja).trim()) errors.push(`${name}: the title is empty.`);
      else {
        const miss = ["ko", "en", "ja"].filter((l) => !t[l].trim());
        if (miss.length) warns.push(`${name} (${t.en || t.ko || t.ja}): missing title in ${miss.join("/")}.`);
      }
      if (!w.image) warns.push(`${name}: no thumbnail.`);
      if (!w.hero) warns.push(`${name}: no hero image.`);
    });
    return { errors, warns };
  }

  async function publish() {
    const c = compute();
    if (!(c.wChanged || c.sChanged || c.up.length)) { A.toast("There is nothing to publish."); return; }
    const v = validate(c);
    if (v.errors.length) { A.toast(v.errors[0], "err"); return; }

    const total = c.up.reduce((n, p) => n + S.files.get(p).blob.size, 0);
    const lines = [];
    if (c.wChanged) lines.push("Works data (data/works.js)");
    if (c.sChanged) lines.push("About data (data/site.js)");
    if (c.newPages.length) lines.push(`Create ${c.newPages.length} new work page${c.newPages.length === 1 ? "" : "s"}`);
    if (c.delPages.length) lines.push(`Delete ${c.delPages.length} work page${c.delPages.length === 1 ? "" : "s"}`);
    if (c.up.length) lines.push(`Upload ${c.up.length} file${c.up.length === 1 ? "" : "s"} (${A.fmtSize(total)})`);
    const delBox = h("input", { type: "checkbox", checked: true });
    const body = h("div", null,
      h("ul", null, lines.map((l) => h("li", { text: l }))),
      c.orphans.length ? h("label", { class: "chk" }, delBox, ` Also delete ${c.orphans.length} unused image${c.orphans.length === 1 ? "" : "s"} from the repository`) : null,
      v.warns.length ? h("div", { class: "note-box" }, h("b", { text: "Please check" }), h("ul", null, v.warns.slice(0, 8).map((w) => h("li", { text: w })), v.warns.length > 8 ? h("li", { text: `…and ${v.warns.length - 8} more` }) : null)) : null,
      A.hint("Publishing commits to GitHub. The site updates in 1 to 3 minutes.")
    );
    const ok = await modal("Publish now?", body, [{ text: "Cancel", value: false, cls: "ghost" }, { text: "Publish", value: true }]);
    if (!ok) return;
    const delOrphans = c.orphans.length > 0 && delBox.checked;

    try {
      barPub.disabled = true;
      await busy("Preparing…", async (prog) => {
        const changes = [];
        if (c.wChanged) changes.push({ path: "data/works.js", content: A.dataFileText(WORKS_HEADER, "WORKS_DATA", c.works) });
        if (c.sChanged) changes.push({ path: "data/site.js", content: A.dataFileText(SITE_HEADER, "SITE_DATA", JSON.parse(c.sj)) });

        if (c.newPages.length) {
          prog("Reading the work page template…");
          const tpl = [...S.tree].filter((p) => /^works\/project-\d+\.html$/.test(p)).sort()[0];
          if (!tpl) throw new Error("Could not find a works/project-NN.html template in the repository.");
          const html = await ctx.gh.getText(tpl);
          if (!html || !/data-work-id="[^"]*"/.test(html)) throw new Error(tpl + " has an unexpected format.");
          c.newPages.forEach((id) => changes.push({ path: pagePath(id), content: html.replace(/data-work-id="[^"]*"/, `data-work-id="${id}"`) }));
        }
        c.delPages.forEach((id) => changes.push({ path: pagePath(id), content: null }));
        for (const p of c.up) changes.push({ path: p, content: await A.bytesOf(S.files.get(p).blob) });
        if (delOrphans) c.orphans.forEach((p) => changes.push({ path: p, content: null }));

        const parts = [];
        if (c.wChanged) parts.push("works");
        if (c.sChanged) parts.push("about");
        if (c.up.length) parts.push(c.up.length + " files");
        await ctx.gh.commit("Admin: update " + parts.join(", "), changes, (n, t) => prog(`Uploading ${n}/${t}`, Math.round((n / t) * 90)));
        prog("Finishing…", 100);

        c.up.forEach((p) => S.tree.add(p));
        c.newPages.forEach((id) => S.tree.add(pagePath(id)));
        c.delPages.forEach((id) => S.tree.delete(pagePath(id)));
        if (delOrphans) c.orphans.forEach((p) => S.tree.delete(p));
      });
      S.markPublished();
      baseline(c.works);
      saveSession();
      A.toast("Published. The site will update in 1 to 3 minutes.", "ok");
      render();
    } catch (e) {
      A.toast("Publish failed: " + friendly(e), "err");
    }
    barPub.disabled = false;
    updateBar();
  }

  /* =========================================================
     Start
     ========================================================= */
  async function enter() {
    try {
      await busy("Loading from the repository…", loadData);
    } catch (e) {
      if (e.status === 401 || e.status === 403) store.del("sessionStorage", SESSION);
      gate("Could not load", null,
        h("p", { class: "err", text: friendly(e) }),
        h("div", { class: "btns" },
          h("button", { class: "btn", type: "button", text: "Start over", onclick: boot }),
          h("button", { class: "btn ghost", type: "button", text: "Try again", onclick: enter })
        )
      );
      return;
    }
    tab = "works";
    buildShell();
    render();
  }

  async function boot() {
    if (window.matchMedia("(max-width: 768px), (hover: none) and (pointer: coarse)").matches) {
      app.replaceChildren(h("p", { class: "boot", text: "The admin page is available on desktop only." }));
      return;
    }
    app.replaceChildren(h("p", { class: "boot", text: "Loading…" }));
    const s = readSession();
    if (s) {
      ctx.gh = new A.GH(s);
      await enter();
      return;
    }
    let vault = null;
    try {
      const r = await fetch("vault.json", { cache: "no-store" });
      if (r.ok) vault = await r.json();
      else if (r.status !== 404) throw new Error("Could not read vault.json (" + r.status + ")");
    } catch (e) {
      gate("Cannot connect", null, h("p", { class: "err", text: "Open the admin page from the web server (https://eunsumoon.com/admin/). " + (e.message || "") }));
      return;
    }
    if (vault && vault.ct) renderLogin(vault);
    else renderSetup();
  }

  boot();
})(window.Admin);
